package com.cdm.depaul.coffeeShop.controllers;

import com.cdm.depaul.coffeeShop.services.CustomerService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;

import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@Controller
@Component
@Scope("singleton")
public class CoffeeShopController {

    @Autowired
    private CustomerService customerService;

    public CoffeeShopController() {}

    @RequestMapping(value = {"/", "/home"})
    public String home (HttpServletRequest request, HttpServletResponse response, Model model) {
       Cookie homeCookie = new Cookie("Customer", "customer");
       homeCookie.setMaxAge(60 * 60);
       /*
        Domain that the client should use to return this cookie
        Could not be set and it will be autogenerated.
        */
        homeCookie.setDomain("localhost");
        response.addCookie(homeCookie);
        model.addAttribute("maxAge", homeCookie.getMaxAge());
        model.addAttribute("cookName", homeCookie.getName());
        model.addAttribute("cookVal", homeCookie.getValue());
        model.addAttribute("cookPath", homeCookie.getPath());
        return "home";
    }


    @RequestMapping(value = {"/products"})
    public String products (HttpServletRequest request, HttpServletResponse response, Model model) {
        return "products";
    }


    @RequestMapping(value = {"/shoppingcart"})
    public String shoppingCart (HttpServletRequest request, HttpServletResponse response, Model model) {
        return "shopping";
    }

    @RequestMapping(value = {"/products/coffee"})
    public String coffeeProducts(HttpServletResponse response, HttpServletRequest request, Model model) {
        return "coffeeProducts";
    }
}
